/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BUSCAMINAS;


/**
 *
 * @author d.pelado.2022
 */
public class CARA_A_CARA_INT extends javax.swing.JFrame {

     private int jgdr1, jdr2, ln;
    private String Usuario;
    public int getJgdr1() {
        return jgdr1;
    }

    public void setJgdr1(int jgdr1) {
        this.jgdr1 = jgdr1;
    }

    public int getJdr2() {
        return jdr2;
    }

    public void setJdr2(int jdr2) {
        this.jdr2 = jdr2;
    }
    
    

    

    /**
     * Creates new form CARA_A_CARA_INT
     */
    public CARA_A_CARA_INT() {
        initComponents();
        
        this.jLabelN1.setText(MAIN.listaJ.get(jgdr1).nombre);
        this.jLabelPJ1.setText(Integer.toString(MAIN.listaJ.get(jgdr1).getStats().getJugadas()));
        this.jLabelPG1.setText(Integer.toString(MAIN.listaJ.get(jgdr1).getStats().getGanadas()));
        this.jLabelPP1.setText(Integer.toString(MAIN.listaJ.get(jgdr1).getStats().getPerdidas()));
        this.jLabelME1.setText(Integer.toString(MAIN.listaJ.get(jgdr1).getStats().getMinas_a_favor()));
        this.jLabelMP1.setText(Integer.toString(MAIN.listaJ.get(jgdr1).getStats().getMinas_en_contra()));    
    
        this.jLabelN2.setText(MAIN.listaJ.get(jdr2).nombre);
        this.jLabelPJ2.setText(Integer.toString(MAIN.listaJ.get(jdr2).getStats().getJugadas()));
        this.jLabelPG2.setText(Integer.toString(MAIN.listaJ.get(jdr2).getStats().getGanadas()));
        this.jLabelPP2.setText(Integer.toString(MAIN.listaJ.get(jdr2).getStats().getPerdidas()));
        this.jLabelME2.setText(Integer.toString(MAIN.listaJ.get(jdr2).getStats().getMinas_a_favor()));
        this.jLabelMP2.setText(  Integer.toString(MAIN.listaJ.get(jdr2).getStats().getMinas_en_contra()));    
    }

    public CARA_A_CARA_INT(int jgdr1, int jdr2) {
        this.jgdr1 = jgdr1;
        this.jdr2 = jdr2;
        initComponents();
        
        this.jLabelN1.setText(MAIN.listaJ.get(jgdr1).nombre);
        this.jLabelPJ1.setText(Integer.toString(MAIN.listaJ.get(jgdr1).getStats().getJugadas()));
        this.jLabelPG1.setText(Integer.toString(MAIN.listaJ.get(jgdr1).getStats().getGanadas()));
        this.jLabelPP1.setText(Integer.toString(MAIN.listaJ.get(jgdr1).getStats().getPerdidas()));
        this.jLabelME1.setText(Integer.toString(MAIN.listaJ.get(jgdr1).getStats().getMinas_a_favor()));
        this.jLabelMP1.setText(Integer.toString(MAIN.listaJ.get(jgdr1).getStats().getMinas_en_contra()));    
    
        this.jLabelN2.setText(MAIN.listaJ.get(jdr2).nombre);
        this.jLabelPJ2.setText(Integer.toString(MAIN.listaJ.get(jdr2).getStats().getJugadas()));
        this.jLabelPG2.setText(Integer.toString(MAIN.listaJ.get(jdr2).getStats().getGanadas()));
        this.jLabelPP2.setText(Integer.toString(MAIN.listaJ.get(jdr2).getStats().getPerdidas()));
        this.jLabelME2.setText(Integer.toString(MAIN.listaJ.get(jdr2).getStats().getMinas_a_favor()));
        this.jLabelMP2.setText(  Integer.toString(MAIN.listaJ.get(jdr2).getStats().getMinas_en_contra()));    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelN1 = new javax.swing.JLabel();
        jLabelN2 = new javax.swing.JLabel();
        jLabelPJ1 = new javax.swing.JLabel();
        jLabelPJ2 = new javax.swing.JLabel();
        jLabelPG1 = new javax.swing.JLabel();
        jLabelPG2 = new javax.swing.JLabel();
        jLabelPP1 = new javax.swing.JLabel();
        jLabelPP2 = new javax.swing.JLabel();
        jLabelME1 = new javax.swing.JLabel();
        jLabelME2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelMP1 = new javax.swing.JLabel();
        jLabelMP2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("CARA A CARA");

        jLabel2.setText("Partidas Jugadas");

        jLabel3.setText("Partidas Perdidas");

        jLabel4.setText("Partidas Ganadas");

        jLabel5.setText("Minas encontradas");

        jLabel6.setText("Vs");

        jLabel7.setText("Vs");

        jLabel8.setText("Vs");

        jLabel9.setText("Vs");

        jLabel10.setText("Vs");

        jLabelN1.setText("jLabel11");

        jLabelN2.setText("jLabel12");

        jLabelPJ1.setText("jLabel13");

        jLabelPJ2.setText("jLabel14");

        jLabelPG1.setText("jLabel15");

        jLabelPG2.setText("jLabel16");

        jLabelPP1.setText("jLabel17");

        jLabelPP2.setText("jLabel18");

        jLabelME1.setText("jLabel19");

        jLabelME2.setText("jLabel20");

        jLabel11.setText("Minas Perdidas");

        jLabelMP1.setText("jLabel12");

        jLabelMP2.setText("jLabel13");

        jLabel12.setText("Vs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMP1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPJ1)
                                    .addComponent(jLabelN1)
                                    .addComponent(jLabelPG1)
                                    .addComponent(jLabelPP1)
                                    .addComponent(jLabelME1))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelN2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPJ2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPG2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPP2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelME2)
                                    .addComponent(jLabelMP2))))
                        .addGap(25, 25, 25)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelN1)
                    .addComponent(jLabelN2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabelPJ1)
                    .addComponent(jLabelPJ2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabelPG1)
                    .addComponent(jLabelPG2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabelPP1)
                    .addComponent(jLabelPP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabelME1)
                    .addComponent(jLabelME2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMP1)
                    .addComponent(jLabel11)
                    .addComponent(jLabelMP2)
                    .addComponent(jLabel12))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CARA_A_CARA_INT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CARA_A_CARA_INT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CARA_A_CARA_INT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CARA_A_CARA_INT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CARA_A_CARA_INT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelME1;
    private javax.swing.JLabel jLabelME2;
    private javax.swing.JLabel jLabelMP1;
    private javax.swing.JLabel jLabelMP2;
    private javax.swing.JLabel jLabelN1;
    private javax.swing.JLabel jLabelN2;
    private javax.swing.JLabel jLabelPG1;
    private javax.swing.JLabel jLabelPG2;
    private javax.swing.JLabel jLabelPJ1;
    private javax.swing.JLabel jLabelPJ2;
    private javax.swing.JLabel jLabelPP1;
    private javax.swing.JLabel jLabelPP2;
    // End of variables declaration//GEN-END:variables
}
