/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BUSCAMINAS;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import static java.util.Arrays.toString;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author g.lara.2022
 */
public class CARGAR_JUGADORES extends javax.swing.JFrame {
    File f = new File ("C:\\BUSCAMINAS\\note");
   ArrayList<Jugador> JGDR= new ArrayList<>();
   int ln;
    public CARGAR_JUGADORES() {
        initComponents();
    }
    
    
      private void crearArchivo(String aux)
    {
         try{
            FileReader fr = new FileReader(f+"\\"+aux);
            System.err.println("EXISTE EL ARCHIVO");
        } catch (FileNotFoundException ex)
        {
            try {
                FileWriter fw = new FileWriter(f+"\\"+aux);
                System.out.println("ARCHIVO CREADO");
            } catch(IOException ex1)
            {
                Logger.getLogger(DEFAULT.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }
      
      private void numeroLineas(String adress)
    {
        try
        {
            ln=1;
            RandomAccessFile raf = new RandomAccessFile(adress,"rw");
            for(int i=0; raf.readLine()!= null; i++)
            {
                ln++;
            }
            ln--;
        } catch (FileNotFoundException ex)
        {
            Logger.getLogger(DEFAULT.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DEFAULT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
      
      void escribir()
      {
        try {
            RandomAccessFile raf = new RandomAccessFile (f+"\\loginsJ.txt", "rw");
            for(int i = 0; i <ln;i++)
            {
                raf.readLine();
            }
            for(int i = 0; i< this.JGDR.size();i++)
            {
            raf.writeBytes("\r\n");
            raf.writeBytes("\r\n");
            raf.writeBytes("Usuario:"+this.JGDR.get(i).nombre+"\r\n");
            raf.writeBytes("Contrasena:"+this.JGDR.get(i).contraseña+"\r\n");
            raf.writeBytes("Partidas Jugadas:0\r\n");
            raf.writeBytes("Partidas Ganadas:0\r\n");
            raf.writeBytes("Partidas Perdidas:0\r\n");
            raf.writeBytes("Minas a favor:0\r\n");
            raf.writeBytes("Minas en contra:0\r\n");
            }
        } 
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(DEFAULT.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) 
        {
            Logger.getLogger(DEFAULT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      
    void cargar(String aux)
    {
        try {
            RandomAccessFile raf = new RandomAccessFile(f+"\\"+aux,"rw");
            int amnt = Integer.parseInt(raf.readLine());
            raf.readLine();
            for(int i = 0; i < amnt - 1 ; i++)
            {
                String jdr = raf.readLine() ;
                String[] partes = jdr.split("#");
                Jugador jgdr = new Jugador(partes[0],partes[1]);
                this.JGDR.add(jgdr);
                MAIN.listaJ.add(jgdr);
                if(i != amnt -2)
                {
                    raf.readLine();
                }
            }
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CARGAR_JUGADORES.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CARGAR_JUGADORES.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ESCRIBA LA DIRECCION DEL ARCHIVO");

        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("DIRECCION:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       String aux = jLabel1.getText();
       cargar(aux);
       numeroLineas("C:\\BUSCAMINAS\\note\\loginsJ.txt");
       escribir();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CARGAR_JUGADORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CARGAR_JUGADORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CARGAR_JUGADORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CARGAR_JUGADORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CARGAR_JUGADORES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
