/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BUSCAMINAS;

/**
 *
 * @author d.pelado.2022
 */
public class Perfil_Jugador extends javax.swing.JFrame {

    /**
     * Creates new form Perfil_Jugador
     */
    
    
    
    private int pos;

    public void setJdr(int pos) {
        this.pos = pos;
    }
    
    public Perfil_Jugador()
    {
        initComponents();
        this.jLabel2.setText(MAIN.listaJ.get(pos).nombre);
        this.jLabel3.setText( Integer.toString(MAIN.listaJ.get(pos).getStats().getJugadas()));
        this.jLabel4.setText(Integer.toString(MAIN.listaJ.get(pos).getStats().getGanadas()));
        this.jLabel5.setText( Integer.toString(MAIN.listaJ.get(pos).getStats().getPerdidas()));
        this.jLabel6.setText( Integer.toString(MAIN.listaJ.get(pos).getStats().getMinas_a_favor()));
        this.jLabel7.setText(Integer.toString(MAIN.listaJ.get(pos).getStats().getMinas_en_contra()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlnombre = new javax.swing.JLabel();
        jlpartidas_jugadas = new javax.swing.JLabel();
        jlpartidas_ganadas = new javax.swing.JLabel();
        jlpartidas_perdidas = new javax.swing.JLabel();
        jlminas_encontradas = new javax.swing.JLabel();
        jlminas_encontradas1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Perfil Jugador");

        jlnombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlnombre.setText("Nombre");

        jlpartidas_jugadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlpartidas_jugadas.setText("Partidas Jugadas");

        jlpartidas_ganadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlpartidas_ganadas.setText("Partidas Ganadas");

        jlpartidas_perdidas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlpartidas_perdidas.setText("Partidas Perdidas");

        jlminas_encontradas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlminas_encontradas.setText("Minas Encontradas");

        jlminas_encontradas1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlminas_encontradas1.setText("Minas Perdidas");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlnombre)
                            .addComponent(jlpartidas_jugadas)
                            .addComponent(jlpartidas_ganadas)
                            .addComponent(jlpartidas_perdidas)
                            .addComponent(jlminas_encontradas)
                            .addComponent(jlminas_encontradas1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(122, 122, 122))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnombre)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlpartidas_jugadas)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpartidas_ganadas)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlpartidas_perdidas)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlminas_encontradas)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlminas_encontradas1)
                    .addComponent(jLabel7))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil_Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil_Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil_Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil_Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil_Jugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlminas_encontradas;
    private javax.swing.JLabel jlminas_encontradas1;
    private javax.swing.JLabel jlnombre;
    private javax.swing.JLabel jlpartidas_ganadas;
    private javax.swing.JLabel jlpartidas_jugadas;
    private javax.swing.JLabel jlpartidas_perdidas;
    // End of variables declaration//GEN-END:variables
}
